@startmindmap opensource-mindmap
-[#Orange] Open Source
-- Open
--- Accessible
---- Diversity
----- Code of Conduct
--- Free
---- Gratis
----- License
---- Libre
--- Clear
---- Goals
---- Vision
--- Wide
++ Source
+++ Origin
++++ Business
+++++ Profit
+++++ Non-Profit
++++ Person
+++ Spring
+++ Root
+++ Begin

@endmindmap