@startmindmap opensource-mindmap
-[#Orange] Open Source
-- Open
--- Free
--- Colleberation
++ Source
+++ Code
+++ Processes
+++ Goverance
+++ People
+++ Art
+++ Software
++++ Code
+++ Hardware
++++ CPU
@endmindmap